# Generated by Django 2.1.7 on 2019-02-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='modules',
        ),
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
