# Generated by Django 2.1.3 on 2019-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='twenty_four_hours',
            field=models.BooleanField(default=True),
        ),
    ]
