# Generated by Django 2.1.3 on 2019-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0002_datetime_twenty_four_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='current_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetime',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
