# Generated by Django 2.1.3 on 2019-02-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0003_auto_20190227_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimes', to='dashboard.Module'),
        ),
    ]
