# Generated by Django 2.1.3 on 2019-03-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0004_auto_20190227_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dt', to='dashboard.Module'),
        ),
    ]
