# Generated by Django 2.1.7 on 2019-02-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('dashboard', '0002_module_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
