# Generated by Django 2.1.7 on 2019-02-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190214_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ModuleType'),
        ),
    ]
