# Generated by Django 2.1.3 on 2019-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190214_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='name',
            field=models.CharField(default='blah', max_length=50),
            preserve_default=False,
        ),
    ]
