# Generated by Django 2.1.3 on 2019-02-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_moduletype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.Profile'),
        ),
    ]
