# Generated by Django 2.1.3 on 2019-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190227_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='z_index',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
