# Generated by Django 2.1.3 on 2019-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190303_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
