# Generated by Django 2.1.3 on 2019-03-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190227_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='interval',
            field=models.IntegerField(default=5),
        ),
    ]
