# Generated by Django 2.1.7 on 2019-03-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190304_0015'),
        ('photos', '0004_photos_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photos_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='photos.Photos'),
        ),
    ]
