# Generated by Django 2.1.3 on 2019-03-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190306_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.Module'),
        ),
    ]
