# Generated by Django 2.1.3 on 2019-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190216_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='current_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
