# Generated by Django 2.1.7 on 2019-03-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190227_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='forecast_length',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='show_forecast',
        ),
    ]
