# Generated by Django 2.1.7 on 2019-03-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='unit',
            field=models.CharField(default='fahrenheit', max_length=50),
        ),
    ]
