# Generated by Django 2.1.3 on 2019-03-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecast_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='dashboard.Module'),
        ),
    ]
